//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:39:25 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.customeradd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerRetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerRetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeCreated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeModified" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EditSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClassRef" type="{}ClassRefType"/>
 *         &lt;element name="ParentRef" type="{}ParentRefType"/>
 *         &lt;element name="Sublevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Salutation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillAddress" type="{}BillAddressType"/>
 *         &lt;element name="BillAddressBlock" type="{}BillAddressBlockType"/>
 *         &lt;element name="ShipAddress" type="{}ShipAddressType"/>
 *         &lt;element name="ShipAddressBlock" type="{}ShipAddressBlockType"/>
 *         &lt;element name="ShipToAddress" type="{}ShipToAddressType"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AltPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AltContact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdditionalContactRef" type="{}AdditionalContactRefType"/>
 *         &lt;element name="ContactsRet" type="{}ContactsRetType"/>
 *         &lt;element name="CustomerTypeRef" type="{}CustomerTypeRefType"/>
 *         &lt;element name="TermsRef" type="{}TermsRefType"/>
 *         &lt;element name="SalesRepRef" type="{}SalesRepRefType"/>
 *         &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesTaxCodeRef" type="{}SalesTaxCodeRefType"/>
 *         &lt;element name="ItemSalesTaxRef" type="{}ItemSalesTaxRefType"/>
 *         &lt;element name="ResaleNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreditLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreferredPaymentMethodRef" type="{}PreferredPaymentMethodRefType"/>
 *         &lt;element name="CreditCardInfo" type="{}CreditCardInfoType"/>
 *         &lt;element name="JobStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobProjectedEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobTypeRef" type="{}JobTypeRefType"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdditionalNotesRet" type="{}AdditionalNotesRetType"/>
 *         &lt;element name="PreferredDeliveryMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PriceLevelRef" type="{}PriceLevelRefType"/>
 *         &lt;element name="ExternalGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrencyRef" type="{}CurrencyRefType"/>
 *         &lt;element name="DataExtRet" type="{}DataExtRetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerRetType", propOrder = {
    "listID",
    "timeCreated",
    "timeModified",
    "editSequence",
    "name",
    "fullName",
    "isActive",
    "classRef",
    "parentRef",
    "sublevel",
    "companyName",
    "salutation",
    "firstName",
    "middleName",
    "lastName",
    "jobTitle",
    "billAddress",
    "billAddressBlock",
    "shipAddress",
    "shipAddressBlock",
    "shipToAddress",
    "phone",
    "altPhone",
    "fax",
    "email",
    "cc",
    "contact",
    "altContact",
    "additionalContactRef",
    "contactsRet",
    "customerTypeRef",
    "termsRef",
    "salesRepRef",
    "balance",
    "totalBalance",
    "salesTaxCodeRef",
    "itemSalesTaxRef",
    "resaleNumber",
    "accountNumber",
    "creditLimit",
    "preferredPaymentMethodRef",
    "creditCardInfo",
    "jobStatus",
    "jobStartDate",
    "jobProjectedEndDate",
    "jobEndDate",
    "jobDesc",
    "jobTypeRef",
    "notes",
    "additionalNotesRet",
    "preferredDeliveryMethod",
    "priceLevelRef",
    "externalGUID",
    "currencyRef",
    "dataExtRet"
})
public class CustomerRetType {

    @XmlElement(name = "ListID", required = true)
    protected String listID;
    @XmlElement(name = "TimeCreated", required = true)
    protected String timeCreated;
    @XmlElement(name = "TimeModified", required = true)
    protected String timeModified;
    @XmlElement(name = "EditSequence", required = true)
    protected String editSequence;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "FullName", required = true)
    protected String fullName;
    @XmlElement(name = "IsActive", required = true)
    protected String isActive;
    @XmlElement(name = "ClassRef", required = true)
    protected ClassRefType classRef;
    @XmlElement(name = "ParentRef", required = true)
    protected ParentRefType parentRef;
    @XmlElement(name = "Sublevel", required = true)
    protected String sublevel;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "Salutation", required = true)
    protected String salutation;
    @XmlElement(name = "FirstName", required = true)
    protected String firstName;
    @XmlElement(name = "MiddleName", required = true)
    protected String middleName;
    @XmlElement(name = "LastName", required = true)
    protected String lastName;
    @XmlElement(name = "JobTitle", required = true)
    protected String jobTitle;
    @XmlElement(name = "BillAddress", required = true)
    protected BillAddressType billAddress;
    @XmlElement(name = "BillAddressBlock", required = true)
    protected BillAddressBlockType billAddressBlock;
    @XmlElement(name = "ShipAddress", required = true)
    protected ShipAddressType shipAddress;
    @XmlElement(name = "ShipAddressBlock", required = true)
    protected ShipAddressBlockType shipAddressBlock;
    @XmlElement(name = "ShipToAddress", required = true)
    protected ShipToAddressType shipToAddress;
    @XmlElement(name = "Phone", required = true)
    protected String phone;
    @XmlElement(name = "AltPhone", required = true)
    protected String altPhone;
    @XmlElement(name = "Fax", required = true)
    protected String fax;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Cc", required = true)
    protected String cc;
    @XmlElement(name = "Contact", required = true)
    protected String contact;
    @XmlElement(name = "AltContact", required = true)
    protected String altContact;
    @XmlElement(name = "AdditionalContactRef", required = true)
    protected AdditionalContactRefType additionalContactRef;
    @XmlElement(name = "ContactsRet", required = true)
    protected ContactsRetType contactsRet;
    @XmlElement(name = "CustomerTypeRef", required = true)
    protected CustomerTypeRefType customerTypeRef;
    @XmlElement(name = "TermsRef", required = true)
    protected TermsRefType termsRef;
    @XmlElement(name = "SalesRepRef", required = true)
    protected SalesRepRefType salesRepRef;
    @XmlElement(name = "Balance", required = true)
    protected String balance;
    @XmlElement(name = "TotalBalance", required = true)
    protected String totalBalance;
    @XmlElement(name = "SalesTaxCodeRef", required = true)
    protected SalesTaxCodeRefType salesTaxCodeRef;
    @XmlElement(name = "ItemSalesTaxRef", required = true)
    protected ItemSalesTaxRefType itemSalesTaxRef;
    @XmlElement(name = "ResaleNumber", required = true)
    protected String resaleNumber;
    @XmlElement(name = "AccountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "CreditLimit", required = true)
    protected String creditLimit;
    @XmlElement(name = "PreferredPaymentMethodRef", required = true)
    protected PreferredPaymentMethodRefType preferredPaymentMethodRef;
    @XmlElement(name = "CreditCardInfo", required = true)
    protected CreditCardInfoType creditCardInfo;
    @XmlElement(name = "JobStatus", required = true)
    protected String jobStatus;
    @XmlElement(name = "JobStartDate", required = true)
    protected String jobStartDate;
    @XmlElement(name = "JobProjectedEndDate", required = true)
    protected String jobProjectedEndDate;
    @XmlElement(name = "JobEndDate", required = true)
    protected String jobEndDate;
    @XmlElement(name = "JobDesc", required = true)
    protected String jobDesc;
    @XmlElement(name = "JobTypeRef", required = true)
    protected JobTypeRefType jobTypeRef;
    @XmlElement(name = "Notes", required = true)
    protected String notes;
    @XmlElement(name = "AdditionalNotesRet", required = true)
    protected AdditionalNotesRetType additionalNotesRet;
    @XmlElement(name = "PreferredDeliveryMethod", required = true)
    protected String preferredDeliveryMethod;
    @XmlElement(name = "PriceLevelRef", required = true)
    protected PriceLevelRefType priceLevelRef;
    @XmlElement(name = "ExternalGUID", required = true)
    protected String externalGUID;
    @XmlElement(name = "CurrencyRef", required = true)
    protected CurrencyRefType currencyRef;
    @XmlElement(name = "DataExtRet", required = true)
    protected DataExtRetType dataExtRet;

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListID(String value) {
        this.listID = value;
    }

    /**
     * Gets the value of the timeCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeCreated() {
        return timeCreated;
    }

    /**
     * Sets the value of the timeCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeCreated(String value) {
        this.timeCreated = value;
    }

    /**
     * Gets the value of the timeModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeModified() {
        return timeModified;
    }

    /**
     * Sets the value of the timeModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeModified(String value) {
        this.timeModified = value;
    }

    /**
     * Gets the value of the editSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditSequence() {
        return editSequence;
    }

    /**
     * Sets the value of the editSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditSequence(String value) {
        this.editSequence = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActive(String value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the classRef property.
     * 
     * @return
     *     possible object is
     *     {@link ClassRefType }
     *     
     */
    public ClassRefType getClassRef() {
        return classRef;
    }

    /**
     * Sets the value of the classRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassRefType }
     *     
     */
    public void setClassRef(ClassRefType value) {
        this.classRef = value;
    }

    /**
     * Gets the value of the parentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRefType }
     *     
     */
    public ParentRefType getParentRef() {
        return parentRef;
    }

    /**
     * Sets the value of the parentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRefType }
     *     
     */
    public void setParentRef(ParentRefType value) {
        this.parentRef = value;
    }

    /**
     * Gets the value of the sublevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSublevel() {
        return sublevel;
    }

    /**
     * Sets the value of the sublevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSublevel(String value) {
        this.sublevel = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the billAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BillAddressType }
     *     
     */
    public BillAddressType getBillAddress() {
        return billAddress;
    }

    /**
     * Sets the value of the billAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillAddressType }
     *     
     */
    public void setBillAddress(BillAddressType value) {
        this.billAddress = value;
    }

    /**
     * Gets the value of the billAddressBlock property.
     * 
     * @return
     *     possible object is
     *     {@link BillAddressBlockType }
     *     
     */
    public BillAddressBlockType getBillAddressBlock() {
        return billAddressBlock;
    }

    /**
     * Sets the value of the billAddressBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillAddressBlockType }
     *     
     */
    public void setBillAddressBlock(BillAddressBlockType value) {
        this.billAddressBlock = value;
    }

    /**
     * Gets the value of the shipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipAddressType }
     *     
     */
    public ShipAddressType getShipAddress() {
        return shipAddress;
    }

    /**
     * Sets the value of the shipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipAddressType }
     *     
     */
    public void setShipAddress(ShipAddressType value) {
        this.shipAddress = value;
    }

    /**
     * Gets the value of the shipAddressBlock property.
     * 
     * @return
     *     possible object is
     *     {@link ShipAddressBlockType }
     *     
     */
    public ShipAddressBlockType getShipAddressBlock() {
        return shipAddressBlock;
    }

    /**
     * Sets the value of the shipAddressBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipAddressBlockType }
     *     
     */
    public void setShipAddressBlock(ShipAddressBlockType value) {
        this.shipAddressBlock = value;
    }

    /**
     * Gets the value of the shipToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipToAddressType }
     *     
     */
    public ShipToAddressType getShipToAddress() {
        return shipToAddress;
    }

    /**
     * Sets the value of the shipToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipToAddressType }
     *     
     */
    public void setShipToAddress(ShipToAddressType value) {
        this.shipToAddress = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the altPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltPhone() {
        return altPhone;
    }

    /**
     * Sets the value of the altPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltPhone(String value) {
        this.altPhone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the cc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCc() {
        return cc;
    }

    /**
     * Sets the value of the cc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCc(String value) {
        this.cc = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the altContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltContact() {
        return altContact;
    }

    /**
     * Sets the value of the altContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltContact(String value) {
        this.altContact = value;
    }

    /**
     * Gets the value of the additionalContactRef property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalContactRefType }
     *     
     */
    public AdditionalContactRefType getAdditionalContactRef() {
        return additionalContactRef;
    }

    /**
     * Sets the value of the additionalContactRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalContactRefType }
     *     
     */
    public void setAdditionalContactRef(AdditionalContactRefType value) {
        this.additionalContactRef = value;
    }

    /**
     * Gets the value of the contactsRet property.
     * 
     * @return
     *     possible object is
     *     {@link ContactsRetType }
     *     
     */
    public ContactsRetType getContactsRet() {
        return contactsRet;
    }

    /**
     * Sets the value of the contactsRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactsRetType }
     *     
     */
    public void setContactsRet(ContactsRetType value) {
        this.contactsRet = value;
    }

    /**
     * Gets the value of the customerTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerTypeRefType }
     *     
     */
    public CustomerTypeRefType getCustomerTypeRef() {
        return customerTypeRef;
    }

    /**
     * Sets the value of the customerTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerTypeRefType }
     *     
     */
    public void setCustomerTypeRef(CustomerTypeRefType value) {
        this.customerTypeRef = value;
    }

    /**
     * Gets the value of the termsRef property.
     * 
     * @return
     *     possible object is
     *     {@link TermsRefType }
     *     
     */
    public TermsRefType getTermsRef() {
        return termsRef;
    }

    /**
     * Sets the value of the termsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermsRefType }
     *     
     */
    public void setTermsRef(TermsRefType value) {
        this.termsRef = value;
    }

    /**
     * Gets the value of the salesRepRef property.
     * 
     * @return
     *     possible object is
     *     {@link SalesRepRefType }
     *     
     */
    public SalesRepRefType getSalesRepRef() {
        return salesRepRef;
    }

    /**
     * Sets the value of the salesRepRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesRepRefType }
     *     
     */
    public void setSalesRepRef(SalesRepRefType value) {
        this.salesRepRef = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalance(String value) {
        this.balance = value;
    }

    /**
     * Gets the value of the totalBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalBalance() {
        return totalBalance;
    }

    /**
     * Sets the value of the totalBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalBalance(String value) {
        this.totalBalance = value;
    }

    /**
     * Gets the value of the salesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link SalesTaxCodeRefType }
     *     
     */
    public SalesTaxCodeRefType getSalesTaxCodeRef() {
        return salesTaxCodeRef;
    }

    /**
     * Sets the value of the salesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesTaxCodeRefType }
     *     
     */
    public void setSalesTaxCodeRef(SalesTaxCodeRefType value) {
        this.salesTaxCodeRef = value;
    }

    /**
     * Gets the value of the itemSalesTaxRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemSalesTaxRefType }
     *     
     */
    public ItemSalesTaxRefType getItemSalesTaxRef() {
        return itemSalesTaxRef;
    }

    /**
     * Sets the value of the itemSalesTaxRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemSalesTaxRefType }
     *     
     */
    public void setItemSalesTaxRef(ItemSalesTaxRefType value) {
        this.itemSalesTaxRef = value;
    }

    /**
     * Gets the value of the resaleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResaleNumber() {
        return resaleNumber;
    }

    /**
     * Sets the value of the resaleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResaleNumber(String value) {
        this.resaleNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimit(String value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the preferredPaymentMethodRef property.
     * 
     * @return
     *     possible object is
     *     {@link PreferredPaymentMethodRefType }
     *     
     */
    public PreferredPaymentMethodRefType getPreferredPaymentMethodRef() {
        return preferredPaymentMethodRef;
    }

    /**
     * Sets the value of the preferredPaymentMethodRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferredPaymentMethodRefType }
     *     
     */
    public void setPreferredPaymentMethodRef(PreferredPaymentMethodRefType value) {
        this.preferredPaymentMethodRef = value;
    }

    /**
     * Gets the value of the creditCardInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardInfoType }
     *     
     */
    public CreditCardInfoType getCreditCardInfo() {
        return creditCardInfo;
    }

    /**
     * Sets the value of the creditCardInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardInfoType }
     *     
     */
    public void setCreditCardInfo(CreditCardInfoType value) {
        this.creditCardInfo = value;
    }

    /**
     * Gets the value of the jobStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * Sets the value of the jobStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobStatus(String value) {
        this.jobStatus = value;
    }

    /**
     * Gets the value of the jobStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobStartDate() {
        return jobStartDate;
    }

    /**
     * Sets the value of the jobStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobStartDate(String value) {
        this.jobStartDate = value;
    }

    /**
     * Gets the value of the jobProjectedEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobProjectedEndDate() {
        return jobProjectedEndDate;
    }

    /**
     * Sets the value of the jobProjectedEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobProjectedEndDate(String value) {
        this.jobProjectedEndDate = value;
    }

    /**
     * Gets the value of the jobEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobEndDate() {
        return jobEndDate;
    }

    /**
     * Sets the value of the jobEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobEndDate(String value) {
        this.jobEndDate = value;
    }

    /**
     * Gets the value of the jobDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * Sets the value of the jobDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobDesc(String value) {
        this.jobDesc = value;
    }

    /**
     * Gets the value of the jobTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link JobTypeRefType }
     *     
     */
    public JobTypeRefType getJobTypeRef() {
        return jobTypeRef;
    }

    /**
     * Sets the value of the jobTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobTypeRefType }
     *     
     */
    public void setJobTypeRef(JobTypeRefType value) {
        this.jobTypeRef = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the additionalNotesRet property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalNotesRetType }
     *     
     */
    public AdditionalNotesRetType getAdditionalNotesRet() {
        return additionalNotesRet;
    }

    /**
     * Sets the value of the additionalNotesRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalNotesRetType }
     *     
     */
    public void setAdditionalNotesRet(AdditionalNotesRetType value) {
        this.additionalNotesRet = value;
    }

    /**
     * Gets the value of the preferredDeliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredDeliveryMethod() {
        return preferredDeliveryMethod;
    }

    /**
     * Sets the value of the preferredDeliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredDeliveryMethod(String value) {
        this.preferredDeliveryMethod = value;
    }

    /**
     * Gets the value of the priceLevelRef property.
     * 
     * @return
     *     possible object is
     *     {@link PriceLevelRefType }
     *     
     */
    public PriceLevelRefType getPriceLevelRef() {
        return priceLevelRef;
    }

    /**
     * Sets the value of the priceLevelRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceLevelRefType }
     *     
     */
    public void setPriceLevelRef(PriceLevelRefType value) {
        this.priceLevelRef = value;
    }

    /**
     * Gets the value of the externalGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalGUID() {
        return externalGUID;
    }

    /**
     * Sets the value of the externalGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalGUID(String value) {
        this.externalGUID = value;
    }

    /**
     * Gets the value of the currencyRef property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyRefType }
     *     
     */
    public CurrencyRefType getCurrencyRef() {
        return currencyRef;
    }

    /**
     * Sets the value of the currencyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyRefType }
     *     
     */
    public void setCurrencyRef(CurrencyRefType value) {
        this.currencyRef = value;
    }

    /**
     * Gets the value of the dataExtRet property.
     * 
     * @return
     *     possible object is
     *     {@link DataExtRetType }
     *     
     */
    public DataExtRetType getDataExtRet() {
        return dataExtRet;
    }

    /**
     * Sets the value of the dataExtRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataExtRetType }
     *     
     */
    public void setDataExtRet(DataExtRetType value) {
        this.dataExtRet = value;
    }

}
