//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 06:41:40 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.productquery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mozu.qbintegration.model.qbmodel.productquery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QBXML_QNAME = new QName("", "QBXML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mozu.qbintegration.model.qbmodel.productquery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QBXMLType }
     * 
     */
    public QBXMLType createQBXMLType() {
        return new QBXMLType();
    }

    /**
     * Create an instance of {@link ItemSalesTaxGroupRetType }
     * 
     */
    public ItemSalesTaxGroupRetType createItemSalesTaxGroupRetType() {
        return new ItemSalesTaxGroupRetType();
    }

    /**
     * Create an instance of {@link IncomeAccountRefType }
     * 
     */
    public IncomeAccountRefType createIncomeAccountRefType() {
        return new IncomeAccountRefType();
    }

    /**
     * Create an instance of {@link SalesOrPurchaseType }
     * 
     */
    public SalesOrPurchaseType createSalesOrPurchaseType() {
        return new SalesOrPurchaseType();
    }

    /**
     * Create an instance of {@link DepositToAccountRefType }
     * 
     */
    public DepositToAccountRefType createDepositToAccountRefType() {
        return new DepositToAccountRefType();
    }

    /**
     * Create an instance of {@link ItemFixedAssetRetType }
     * 
     */
    public ItemFixedAssetRetType createItemFixedAssetRetType() {
        return new ItemFixedAssetRetType();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRsType }
     * 
     */
    public QBXMLMsgsRsType createQBXMLMsgsRsType() {
        return new QBXMLMsgsRsType();
    }

    /**
     * Create an instance of {@link PrefVendorRefType }
     * 
     */
    public PrefVendorRefType createPrefVendorRefType() {
        return new PrefVendorRefType();
    }

    /**
     * Create an instance of {@link DataExtRetType }
     * 
     */
    public DataExtRetType createDataExtRetType() {
        return new DataExtRetType();
    }

    /**
     * Create an instance of {@link ItemDiscountRetType }
     * 
     */
    public ItemDiscountRetType createItemDiscountRetType() {
        return new ItemDiscountRetType();
    }

    /**
     * Create an instance of {@link AccountRefType }
     * 
     */
    public AccountRefType createAccountRefType() {
        return new AccountRefType();
    }

    /**
     * Create an instance of {@link ItemServiceRetType }
     * 
     */
    public ItemServiceRetType createItemServiceRetType() {
        return new ItemServiceRetType();
    }

    /**
     * Create an instance of {@link ItemSalesTaxRetType }
     * 
     */
    public ItemSalesTaxRetType createItemSalesTaxRetType() {
        return new ItemSalesTaxRetType();
    }

    /**
     * Create an instance of {@link NameFilterType }
     * 
     */
    public NameFilterType createNameFilterType() {
        return new NameFilterType();
    }

    /**
     * Create an instance of {@link ItemOtherChargeRetType }
     * 
     */
    public ItemOtherChargeRetType createItemOtherChargeRetType() {
        return new ItemOtherChargeRetType();
    }

    /**
     * Create an instance of {@link FixedAssetSalesInfoType }
     * 
     */
    public FixedAssetSalesInfoType createFixedAssetSalesInfoType() {
        return new FixedAssetSalesInfoType();
    }

    /**
     * Create an instance of {@link ItemSalesTaxRefType }
     * 
     */
    public ItemSalesTaxRefType createItemSalesTaxRefType() {
        return new ItemSalesTaxRefType();
    }

    /**
     * Create an instance of {@link UnitOfMeasureSetRefType }
     * 
     */
    public UnitOfMeasureSetRefType createUnitOfMeasureSetRefType() {
        return new UnitOfMeasureSetRefType();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRqType }
     * 
     */
    public QBXMLMsgsRqType createQBXMLMsgsRqType() {
        return new QBXMLMsgsRqType();
    }

    /**
     * Create an instance of {@link COGSAccountRefType }
     * 
     */
    public COGSAccountRefType createCOGSAccountRefType() {
        return new COGSAccountRefType();
    }

    /**
     * Create an instance of {@link NameRangeFilterType }
     * 
     */
    public NameRangeFilterType createNameRangeFilterType() {
        return new NameRangeFilterType();
    }

    /**
     * Create an instance of {@link ItemPaymentRetType }
     * 
     */
    public ItemPaymentRetType createItemPaymentRetType() {
        return new ItemPaymentRetType();
    }

    /**
     * Create an instance of {@link ParentRefType }
     * 
     */
    public ParentRefType createParentRefType() {
        return new ParentRefType();
    }

    /**
     * Create an instance of {@link ItemSubtotalRetType }
     * 
     */
    public ItemSubtotalRetType createItemSubtotalRetType() {
        return new ItemSubtotalRetType();
    }

    /**
     * Create an instance of {@link ExpenseAccountRefType }
     * 
     */
    public ExpenseAccountRefType createExpenseAccountRefType() {
        return new ExpenseAccountRefType();
    }

    /**
     * Create an instance of {@link SalesAndPurchaseType }
     * 
     */
    public SalesAndPurchaseType createSalesAndPurchaseType() {
        return new SalesAndPurchaseType();
    }

    /**
     * Create an instance of {@link ItemInventoryRefType }
     * 
     */
    public ItemInventoryRefType createItemInventoryRefType() {
        return new ItemInventoryRefType();
    }

    /**
     * Create an instance of {@link ItemGroupLineType }
     * 
     */
    public ItemGroupLineType createItemGroupLineType() {
        return new ItemGroupLineType();
    }

    /**
     * Create an instance of {@link ClassRefType }
     * 
     */
    public ClassRefType createClassRefType() {
        return new ClassRefType();
    }

    /**
     * Create an instance of {@link ItemInventoryAssemblyRetType }
     * 
     */
    public ItemInventoryAssemblyRetType createItemInventoryAssemblyRetType() {
        return new ItemInventoryAssemblyRetType();
    }

    /**
     * Create an instance of {@link ItemRefType }
     * 
     */
    public ItemRefType createItemRefType() {
        return new ItemRefType();
    }

    /**
     * Create an instance of {@link ItemQueryRsType }
     * 
     */
    public ItemQueryRsType createItemQueryRsType() {
        return new ItemQueryRsType();
    }

    /**
     * Create an instance of {@link TaxVendorRefType }
     * 
     */
    public TaxVendorRefType createTaxVendorRefType() {
        return new TaxVendorRefType();
    }

    /**
     * Create an instance of {@link SalesTaxCodeRefType }
     * 
     */
    public SalesTaxCodeRefType createSalesTaxCodeRefType() {
        return new SalesTaxCodeRefType();
    }

    /**
     * Create an instance of {@link ItemQueryRqType }
     * 
     */
    public ItemQueryRqType createItemQueryRqType() {
        return new ItemQueryRqType();
    }

    /**
     * Create an instance of {@link ItemInventoryRetType }
     * 
     */
    public ItemInventoryRetType createItemInventoryRetType() {
        return new ItemInventoryRetType();
    }

    /**
     * Create an instance of {@link ItemInventoryAssemblyLineType }
     * 
     */
    public ItemInventoryAssemblyLineType createItemInventoryAssemblyLineType() {
        return new ItemInventoryAssemblyLineType();
    }

    /**
     * Create an instance of {@link PaymentMethodRefType }
     * 
     */
    public PaymentMethodRefType createPaymentMethodRefType() {
        return new PaymentMethodRefType();
    }

    /**
     * Create an instance of {@link AssetAccountRefType }
     * 
     */
    public AssetAccountRefType createAssetAccountRefType() {
        return new AssetAccountRefType();
    }

    /**
     * Create an instance of {@link ItemNonInventoryRetType }
     * 
     */
    public ItemNonInventoryRetType createItemNonInventoryRetType() {
        return new ItemNonInventoryRetType();
    }

    /**
     * Create an instance of {@link ItemGroupRetType }
     * 
     */
    public ItemGroupRetType createItemGroupRetType() {
        return new ItemGroupRetType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QBXMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QBXML")
    public JAXBElement<QBXMLType> createQBXML(QBXMLType value) {
        return new JAXBElement<QBXMLType>(_QBXML_QNAME, QBXMLType.class, null, value);
    }

}
