//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 06:41:40 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.productquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBXMLMsgsRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBXMLMsgsRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemQueryRq" type="{}ItemQueryRqType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="onError" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBXMLMsgsRqType", propOrder = {
    "itemQueryRq"
})
public class QBXMLMsgsRqType {

    @XmlElement(name = "ItemQueryRq", required = true)
    protected ItemQueryRqType itemQueryRq;
    @XmlAttribute(name = "onError")
    protected String onError;

    /**
     * Gets the value of the itemQueryRq property.
     * 
     * @return
     *     possible object is
     *     {@link ItemQueryRqType }
     *     
     */
    public ItemQueryRqType getItemQueryRq() {
        return itemQueryRq;
    }

    /**
     * Sets the value of the itemQueryRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemQueryRqType }
     *     
     */
    public void setItemQueryRq(ItemQueryRqType value) {
        this.itemQueryRq = value;
    }

    /**
     * Gets the value of the onError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnError() {
        return onError;
    }

    /**
     * Sets the value of the onError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnError(String value) {
        this.onError = value;
    }

}
