//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 03:01:40 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.orderupdate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesOrderModType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderModType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TxnID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EditSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRef" type="{}CustomerRefType"/>
 *         &lt;element name="ClassRef" type="{}ClassRefType"/>
 *         &lt;element name="TemplateRef" type="{}TemplateRefType"/>
 *         &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillAddress" type="{}BillAddressType"/>
 *         &lt;element name="ShipAddress" type="{}ShipAddressType"/>
 *         &lt;element name="PONumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TermsRef" type="{}TermsRefType"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesRepRef" type="{}SalesRepRefType"/>
 *         &lt;element name="FOB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipMethodRef" type="{}ShipMethodRefType"/>
 *         &lt;element name="ItemSalesTaxRef" type="{}ItemSalesTaxRefType"/>
 *         &lt;element name="IsManuallyClosed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Memo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerMsgRef" type="{}CustomerMsgRefType"/>
 *         &lt;element name="IsToBePrinted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsToBeEmailed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerSalesTaxCodeRef" type="{}CustomerSalesTaxCodeRefType"/>
 *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExchangeRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesOrderLineMod" type="{}SalesOrderLineModType"/>
 *         &lt;element name="SalesOrderLineGroupMod" type="{}SalesOrderLineGroupModType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderModType", propOrder = {
    "txnID",
    "editSequence",
    "customerRef",
    "classRef",
    "templateRef",
    "txnDate",
    "refNumber",
    "billAddress",
    "shipAddress",
    "poNumber",
    "termsRef",
    "dueDate",
    "salesRepRef",
    "fob",
    "shipDate",
    "shipMethodRef",
    "itemSalesTaxRef",
    "isManuallyClosed",
    "memo",
    "customerMsgRef",
    "isToBePrinted",
    "isToBeEmailed",
    "customerSalesTaxCodeRef",
    "other",
    "exchangeRate",
    "salesOrderLineMod",
    "salesOrderLineGroupMod"
})
public class SalesOrderModType {

    @XmlElement(name = "TxnID", required = true)
    protected String txnID;
    @XmlElement(name = "EditSequence", required = true)
    protected String editSequence;
    @XmlElement(name = "CustomerRef", required = true)
    protected CustomerRefType customerRef;
    @XmlElement(name = "ClassRef", required = true)
    protected ClassRefType classRef;
    @XmlElement(name = "TemplateRef", required = true)
    protected TemplateRefType templateRef;
    @XmlElement(name = "TxnDate", required = true)
    protected String txnDate;
    @XmlElement(name = "RefNumber", required = true)
    protected String refNumber;
    @XmlElement(name = "BillAddress", required = true)
    protected BillAddressType billAddress;
    @XmlElement(name = "ShipAddress", required = true)
    protected ShipAddressType shipAddress;
    @XmlElement(name = "PONumber", required = true)
    protected String poNumber;
    @XmlElement(name = "TermsRef", required = true)
    protected TermsRefType termsRef;
    @XmlElement(name = "DueDate", required = true)
    protected String dueDate;
    @XmlElement(name = "SalesRepRef", required = true)
    protected SalesRepRefType salesRepRef;
    @XmlElement(name = "FOB", required = true)
    protected String fob;
    @XmlElement(name = "ShipDate", required = true)
    protected String shipDate;
    @XmlElement(name = "ShipMethodRef", required = true)
    protected ShipMethodRefType shipMethodRef;
    @XmlElement(name = "ItemSalesTaxRef", required = true)
    protected ItemSalesTaxRefType itemSalesTaxRef;
    @XmlElement(name = "IsManuallyClosed", required = true)
    protected String isManuallyClosed;
    @XmlElement(name = "Memo", required = true)
    protected String memo;
    @XmlElement(name = "CustomerMsgRef", required = true)
    protected CustomerMsgRefType customerMsgRef;
    @XmlElement(name = "IsToBePrinted", required = true)
    protected String isToBePrinted;
    @XmlElement(name = "IsToBeEmailed", required = true)
    protected String isToBeEmailed;
    @XmlElement(name = "CustomerSalesTaxCodeRef", required = true)
    protected CustomerSalesTaxCodeRefType customerSalesTaxCodeRef;
    @XmlElement(name = "Other", required = true)
    protected String other;
    @XmlElement(name = "ExchangeRate", required = true)
    protected String exchangeRate;
    @XmlElement(name = "SalesOrderLineMod", required = true)
    protected SalesOrderLineModType salesOrderLineMod;
    @XmlElement(name = "SalesOrderLineGroupMod", required = true)
    protected SalesOrderLineGroupModType salesOrderLineGroupMod;

    /**
     * Gets the value of the txnID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnID() {
        return txnID;
    }

    /**
     * Sets the value of the txnID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnID(String value) {
        this.txnID = value;
    }

    /**
     * Gets the value of the editSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditSequence() {
        return editSequence;
    }

    /**
     * Sets the value of the editSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditSequence(String value) {
        this.editSequence = value;
    }

    /**
     * Gets the value of the customerRef property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerRefType }
     *     
     */
    public CustomerRefType getCustomerRef() {
        return customerRef;
    }

    /**
     * Sets the value of the customerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerRefType }
     *     
     */
    public void setCustomerRef(CustomerRefType value) {
        this.customerRef = value;
    }

    /**
     * Gets the value of the classRef property.
     * 
     * @return
     *     possible object is
     *     {@link ClassRefType }
     *     
     */
    public ClassRefType getClassRef() {
        return classRef;
    }

    /**
     * Sets the value of the classRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassRefType }
     *     
     */
    public void setClassRef(ClassRefType value) {
        this.classRef = value;
    }

    /**
     * Gets the value of the templateRef property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateRefType }
     *     
     */
    public TemplateRefType getTemplateRef() {
        return templateRef;
    }

    /**
     * Sets the value of the templateRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateRefType }
     *     
     */
    public void setTemplateRef(TemplateRefType value) {
        this.templateRef = value;
    }

    /**
     * Gets the value of the txnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * Sets the value of the txnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnDate(String value) {
        this.txnDate = value;
    }

    /**
     * Gets the value of the refNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNumber() {
        return refNumber;
    }

    /**
     * Sets the value of the refNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNumber(String value) {
        this.refNumber = value;
    }

    /**
     * Gets the value of the billAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BillAddressType }
     *     
     */
    public BillAddressType getBillAddress() {
        return billAddress;
    }

    /**
     * Sets the value of the billAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillAddressType }
     *     
     */
    public void setBillAddress(BillAddressType value) {
        this.billAddress = value;
    }

    /**
     * Gets the value of the shipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipAddressType }
     *     
     */
    public ShipAddressType getShipAddress() {
        return shipAddress;
    }

    /**
     * Sets the value of the shipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipAddressType }
     *     
     */
    public void setShipAddress(ShipAddressType value) {
        this.shipAddress = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the termsRef property.
     * 
     * @return
     *     possible object is
     *     {@link TermsRefType }
     *     
     */
    public TermsRefType getTermsRef() {
        return termsRef;
    }

    /**
     * Sets the value of the termsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermsRefType }
     *     
     */
    public void setTermsRef(TermsRefType value) {
        this.termsRef = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the salesRepRef property.
     * 
     * @return
     *     possible object is
     *     {@link SalesRepRefType }
     *     
     */
    public SalesRepRefType getSalesRepRef() {
        return salesRepRef;
    }

    /**
     * Sets the value of the salesRepRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesRepRefType }
     *     
     */
    public void setSalesRepRef(SalesRepRefType value) {
        this.salesRepRef = value;
    }

    /**
     * Gets the value of the fob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOB() {
        return fob;
    }

    /**
     * Sets the value of the fob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOB(String value) {
        this.fob = value;
    }

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipDate(String value) {
        this.shipDate = value;
    }

    /**
     * Gets the value of the shipMethodRef property.
     * 
     * @return
     *     possible object is
     *     {@link ShipMethodRefType }
     *     
     */
    public ShipMethodRefType getShipMethodRef() {
        return shipMethodRef;
    }

    /**
     * Sets the value of the shipMethodRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipMethodRefType }
     *     
     */
    public void setShipMethodRef(ShipMethodRefType value) {
        this.shipMethodRef = value;
    }

    /**
     * Gets the value of the itemSalesTaxRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemSalesTaxRefType }
     *     
     */
    public ItemSalesTaxRefType getItemSalesTaxRef() {
        return itemSalesTaxRef;
    }

    /**
     * Sets the value of the itemSalesTaxRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemSalesTaxRefType }
     *     
     */
    public void setItemSalesTaxRef(ItemSalesTaxRefType value) {
        this.itemSalesTaxRef = value;
    }

    /**
     * Gets the value of the isManuallyClosed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsManuallyClosed() {
        return isManuallyClosed;
    }

    /**
     * Sets the value of the isManuallyClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsManuallyClosed(String value) {
        this.isManuallyClosed = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

    /**
     * Gets the value of the customerMsgRef property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerMsgRefType }
     *     
     */
    public CustomerMsgRefType getCustomerMsgRef() {
        return customerMsgRef;
    }

    /**
     * Sets the value of the customerMsgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerMsgRefType }
     *     
     */
    public void setCustomerMsgRef(CustomerMsgRefType value) {
        this.customerMsgRef = value;
    }

    /**
     * Gets the value of the isToBePrinted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsToBePrinted() {
        return isToBePrinted;
    }

    /**
     * Sets the value of the isToBePrinted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsToBePrinted(String value) {
        this.isToBePrinted = value;
    }

    /**
     * Gets the value of the isToBeEmailed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsToBeEmailed() {
        return isToBeEmailed;
    }

    /**
     * Sets the value of the isToBeEmailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsToBeEmailed(String value) {
        this.isToBeEmailed = value;
    }

    /**
     * Gets the value of the customerSalesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerSalesTaxCodeRefType }
     *     
     */
    public CustomerSalesTaxCodeRefType getCustomerSalesTaxCodeRef() {
        return customerSalesTaxCodeRef;
    }

    /**
     * Sets the value of the customerSalesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerSalesTaxCodeRefType }
     *     
     */
    public void setCustomerSalesTaxCodeRef(CustomerSalesTaxCodeRefType value) {
        this.customerSalesTaxCodeRef = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeRate(String value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the salesOrderLineMod property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderLineModType }
     *     
     */
    public SalesOrderLineModType getSalesOrderLineMod() {
        return salesOrderLineMod;
    }

    /**
     * Sets the value of the salesOrderLineMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderLineModType }
     *     
     */
    public void setSalesOrderLineMod(SalesOrderLineModType value) {
        this.salesOrderLineMod = value;
    }

    /**
     * Gets the value of the salesOrderLineGroupMod property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderLineGroupModType }
     *     
     */
    public SalesOrderLineGroupModType getSalesOrderLineGroupMod() {
        return salesOrderLineGroupMod;
    }

    /**
     * Sets the value of the salesOrderLineGroupMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderLineGroupModType }
     *     
     */
    public void setSalesOrderLineGroupMod(SalesOrderLineGroupModType value) {
        this.salesOrderLineGroupMod = value;
    }

}
