//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:52:52 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.productadd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemInventoryAddType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemInventoryAddType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BarCode" type="{}BarCodeType"/>
 *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClassRef" type="{}ClassRefType"/>
 *         &lt;element name="ParentRef" type="{}ParentRefType"/>
 *         &lt;element name="ManufacturerPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitOfMeasureSetRef" type="{}UnitOfMeasureSetRefType"/>
 *         &lt;element name="SalesTaxCodeRef" type="{}SalesTaxCodeRefType"/>
 *         &lt;element name="SalesDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IncomeAccountRef" type="{}IncomeAccountRefType"/>
 *         &lt;element name="PurchaseDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PurchaseCost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COGSAccountRef" type="{}COGSAccountRefType"/>
 *         &lt;element name="PrefVendorRef" type="{}PrefVendorRefType"/>
 *         &lt;element name="AssetAccountRef" type="{}AssetAccountRefType"/>
 *         &lt;element name="ReorderPoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Max" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QuantityOnHand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InventoryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExternalGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemInventoryAddType", propOrder = {
    "name",
    "barCode",
    "isActive",
    "classRef",
    "parentRef",
    "manufacturerPartNumber",
    "unitOfMeasureSetRef",
    "salesTaxCodeRef",
    "salesDesc",
    "salesPrice",
    "incomeAccountRef",
    "purchaseDesc",
    "purchaseCost",
    "cogsAccountRef",
    "prefVendorRef",
    "assetAccountRef",
    "reorderPoint",
    "max",
    "quantityOnHand",
    "totalValue",
    "inventoryDate",
    "externalGUID"
})
public class ItemInventoryAddType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "BarCode", required = true)
    protected BarCodeType barCode;
    @XmlElement(name = "IsActive", required = true)
    protected String isActive;
    @XmlElement(name = "ClassRef", required = true)
    protected ClassRefType classRef;
    @XmlElement(name = "ParentRef", required = true)
    protected ParentRefType parentRef;
    @XmlElement(name = "ManufacturerPartNumber", required = true)
    protected String manufacturerPartNumber;
    @XmlElement(name = "UnitOfMeasureSetRef", required = true)
    protected UnitOfMeasureSetRefType unitOfMeasureSetRef;
    @XmlElement(name = "SalesTaxCodeRef", required = true)
    protected SalesTaxCodeRefType salesTaxCodeRef;
    @XmlElement(name = "SalesDesc", required = true)
    protected String salesDesc;
    @XmlElement(name = "SalesPrice", required = true)
    protected String salesPrice;
    @XmlElement(name = "IncomeAccountRef", required = true)
    protected IncomeAccountRefType incomeAccountRef;
    @XmlElement(name = "PurchaseDesc", required = true)
    protected String purchaseDesc;
    @XmlElement(name = "PurchaseCost", required = true)
    protected String purchaseCost;
    @XmlElement(name = "COGSAccountRef", required = true)
    protected COGSAccountRefType cogsAccountRef;
    @XmlElement(name = "PrefVendorRef", required = true)
    protected PrefVendorRefType prefVendorRef;
    @XmlElement(name = "AssetAccountRef", required = true)
    protected AssetAccountRefType assetAccountRef;
    @XmlElement(name = "ReorderPoint", required = true)
    protected String reorderPoint;
    @XmlElement(name = "Max", required = true)
    protected String max;
    @XmlElement(name = "QuantityOnHand", required = true)
    protected String quantityOnHand;
    @XmlElement(name = "TotalValue", required = true)
    protected String totalValue;
    @XmlElement(name = "InventoryDate", required = true)
    protected String inventoryDate;
    @XmlElement(name = "ExternalGUID", required = true)
    protected String externalGUID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return
     *     possible object is
     *     {@link BarCodeType }
     *     
     */
    public BarCodeType getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BarCodeType }
     *     
     */
    public void setBarCode(BarCodeType value) {
        this.barCode = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActive(String value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the classRef property.
     * 
     * @return
     *     possible object is
     *     {@link ClassRefType }
     *     
     */
    public ClassRefType getClassRef() {
        return classRef;
    }

    /**
     * Sets the value of the classRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassRefType }
     *     
     */
    public void setClassRef(ClassRefType value) {
        this.classRef = value;
    }

    /**
     * Gets the value of the parentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRefType }
     *     
     */
    public ParentRefType getParentRef() {
        return parentRef;
    }

    /**
     * Sets the value of the parentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRefType }
     *     
     */
    public void setParentRef(ParentRefType value) {
        this.parentRef = value;
    }

    /**
     * Gets the value of the manufacturerPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerPartNumber() {
        return manufacturerPartNumber;
    }

    /**
     * Sets the value of the manufacturerPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerPartNumber(String value) {
        this.manufacturerPartNumber = value;
    }

    /**
     * Gets the value of the unitOfMeasureSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfMeasureSetRefType }
     *     
     */
    public UnitOfMeasureSetRefType getUnitOfMeasureSetRef() {
        return unitOfMeasureSetRef;
    }

    /**
     * Sets the value of the unitOfMeasureSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfMeasureSetRefType }
     *     
     */
    public void setUnitOfMeasureSetRef(UnitOfMeasureSetRefType value) {
        this.unitOfMeasureSetRef = value;
    }

    /**
     * Gets the value of the salesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link SalesTaxCodeRefType }
     *     
     */
    public SalesTaxCodeRefType getSalesTaxCodeRef() {
        return salesTaxCodeRef;
    }

    /**
     * Sets the value of the salesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesTaxCodeRefType }
     *     
     */
    public void setSalesTaxCodeRef(SalesTaxCodeRefType value) {
        this.salesTaxCodeRef = value;
    }

    /**
     * Gets the value of the salesDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesDesc() {
        return salesDesc;
    }

    /**
     * Sets the value of the salesDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesDesc(String value) {
        this.salesDesc = value;
    }

    /**
     * Gets the value of the salesPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesPrice() {
        return salesPrice;
    }

    /**
     * Sets the value of the salesPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesPrice(String value) {
        this.salesPrice = value;
    }

    /**
     * Gets the value of the incomeAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link IncomeAccountRefType }
     *     
     */
    public IncomeAccountRefType getIncomeAccountRef() {
        return incomeAccountRef;
    }

    /**
     * Sets the value of the incomeAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncomeAccountRefType }
     *     
     */
    public void setIncomeAccountRef(IncomeAccountRefType value) {
        this.incomeAccountRef = value;
    }

    /**
     * Gets the value of the purchaseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDesc() {
        return purchaseDesc;
    }

    /**
     * Sets the value of the purchaseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDesc(String value) {
        this.purchaseDesc = value;
    }

    /**
     * Gets the value of the purchaseCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseCost() {
        return purchaseCost;
    }

    /**
     * Sets the value of the purchaseCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseCost(String value) {
        this.purchaseCost = value;
    }

    /**
     * Gets the value of the cogsAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link COGSAccountRefType }
     *     
     */
    public COGSAccountRefType getCOGSAccountRef() {
        return cogsAccountRef;
    }

    /**
     * Sets the value of the cogsAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link COGSAccountRefType }
     *     
     */
    public void setCOGSAccountRef(COGSAccountRefType value) {
        this.cogsAccountRef = value;
    }

    /**
     * Gets the value of the prefVendorRef property.
     * 
     * @return
     *     possible object is
     *     {@link PrefVendorRefType }
     *     
     */
    public PrefVendorRefType getPrefVendorRef() {
        return prefVendorRef;
    }

    /**
     * Sets the value of the prefVendorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefVendorRefType }
     *     
     */
    public void setPrefVendorRef(PrefVendorRefType value) {
        this.prefVendorRef = value;
    }

    /**
     * Gets the value of the assetAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link AssetAccountRefType }
     *     
     */
    public AssetAccountRefType getAssetAccountRef() {
        return assetAccountRef;
    }

    /**
     * Sets the value of the assetAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetAccountRefType }
     *     
     */
    public void setAssetAccountRef(AssetAccountRefType value) {
        this.assetAccountRef = value;
    }

    /**
     * Gets the value of the reorderPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReorderPoint() {
        return reorderPoint;
    }

    /**
     * Sets the value of the reorderPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReorderPoint(String value) {
        this.reorderPoint = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the quantityOnHand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityOnHand() {
        return quantityOnHand;
    }

    /**
     * Sets the value of the quantityOnHand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityOnHand(String value) {
        this.quantityOnHand = value;
    }

    /**
     * Gets the value of the totalValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalValue() {
        return totalValue;
    }

    /**
     * Sets the value of the totalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalValue(String value) {
        this.totalValue = value;
    }

    /**
     * Gets the value of the inventoryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryDate() {
        return inventoryDate;
    }

    /**
     * Sets the value of the inventoryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryDate(String value) {
        this.inventoryDate = value;
    }

    /**
     * Gets the value of the externalGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalGUID() {
        return externalGUID;
    }

    /**
     * Sets the value of the externalGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalGUID(String value) {
        this.externalGUID = value;
    }

}
