//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:59:17 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qbcustomerquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBXMLMsgsRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBXMLMsgsRsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerQueryRs" type="{}CustomerQueryRsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBXMLMsgsRsType", propOrder = {
    "customerQueryRs"
})
public class QBXMLMsgsRsType {

    @XmlElement(name = "CustomerQueryRs", required = true)
    protected CustomerQueryRsType customerQueryRs;

    /**
     * Gets the value of the customerQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerQueryRsType }
     *     
     */
    public CustomerQueryRsType getCustomerQueryRs() {
        return customerQueryRs;
    }

    /**
     * Sets the value of the customerQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerQueryRsType }
     *     
     */
    public void setCustomerQueryRs(CustomerQueryRsType value) {
        this.customerQueryRs = value;
    }

}
