//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:45:08 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qborderquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListIDWithChildren" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FullNameWithChildren" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityFilterType", propOrder = {
    "listID",
    "fullName",
    "listIDWithChildren",
    "fullNameWithChildren"
})
public class EntityFilterType {

    @XmlElement(name = "ListID", required = true)
    protected String listID;
    @XmlElement(name = "FullName", required = true)
    protected String fullName;
    @XmlElement(name = "ListIDWithChildren", required = true)
    protected String listIDWithChildren;
    @XmlElement(name = "FullNameWithChildren", required = true)
    protected String fullNameWithChildren;

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListID(String value) {
        this.listID = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the listIDWithChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListIDWithChildren() {
        return listIDWithChildren;
    }

    /**
     * Sets the value of the listIDWithChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListIDWithChildren(String value) {
        this.listIDWithChildren = value;
    }

    /**
     * Gets the value of the fullNameWithChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullNameWithChildren() {
        return fullNameWithChildren;
    }

    /**
     * Sets the value of the fullNameWithChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullNameWithChildren(String value) {
        this.fullNameWithChildren = value;
    }

}
