//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:45:08 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qborderquery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mozu.qbintegration.model.qbmodel.qborderquery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QBXML_QNAME = new QName("", "QBXML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mozu.qbintegration.model.qbmodel.qborderquery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QBXMLType }
     * 
     */
    public QBXMLType createQBXMLType() {
        return new QBXMLType();
    }

    /**
     * Create an instance of {@link EntityFilterType }
     * 
     */
    public EntityFilterType createEntityFilterType() {
        return new EntityFilterType();
    }

    /**
     * Create an instance of {@link SalesRepRefType }
     * 
     */
    public SalesRepRefType createSalesRepRefType() {
        return new SalesRepRefType();
    }

    /**
     * Create an instance of {@link SalesOrderLineGroupRetType }
     * 
     */
    public SalesOrderLineGroupRetType createSalesOrderLineGroupRetType() {
        return new SalesOrderLineGroupRetType();
    }

    /**
     * Create an instance of {@link RefNumberRangeFilterType }
     * 
     */
    public RefNumberRangeFilterType createRefNumberRangeFilterType() {
        return new RefNumberRangeFilterType();
    }

    /**
     * Create an instance of {@link ItemGroupRefType }
     * 
     */
    public ItemGroupRefType createItemGroupRefType() {
        return new ItemGroupRefType();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRsType }
     * 
     */
    public QBXMLMsgsRsType createQBXMLMsgsRsType() {
        return new QBXMLMsgsRsType();
    }

    /**
     * Create an instance of {@link DataExtRetType }
     * 
     */
    public DataExtRetType createDataExtRetType() {
        return new DataExtRetType();
    }

    /**
     * Create an instance of {@link CurrencyRefType }
     * 
     */
    public CurrencyRefType createCurrencyRefType() {
        return new CurrencyRefType();
    }

    /**
     * Create an instance of {@link BillAddressBlockType }
     * 
     */
    public BillAddressBlockType createBillAddressBlockType() {
        return new BillAddressBlockType();
    }

    /**
     * Create an instance of {@link ItemSalesTaxRefType }
     * 
     */
    public ItemSalesTaxRefType createItemSalesTaxRefType() {
        return new ItemSalesTaxRefType();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRqType }
     * 
     */
    public QBXMLMsgsRqType createQBXMLMsgsRqType() {
        return new QBXMLMsgsRqType();
    }

    /**
     * Create an instance of {@link OverrideUOMSetRefType }
     * 
     */
    public OverrideUOMSetRefType createOverrideUOMSetRefType() {
        return new OverrideUOMSetRefType();
    }

    /**
     * Create an instance of {@link SalesOrderRetType }
     * 
     */
    public SalesOrderRetType createSalesOrderRetType() {
        return new SalesOrderRetType();
    }

    /**
     * Create an instance of {@link ModifiedDateRangeFilterType }
     * 
     */
    public ModifiedDateRangeFilterType createModifiedDateRangeFilterType() {
        return new ModifiedDateRangeFilterType();
    }

    /**
     * Create an instance of {@link ShipAddressBlockType }
     * 
     */
    public ShipAddressBlockType createShipAddressBlockType() {
        return new ShipAddressBlockType();
    }

    /**
     * Create an instance of {@link InventorySiteRefType }
     * 
     */
    public InventorySiteRefType createInventorySiteRefType() {
        return new InventorySiteRefType();
    }

    /**
     * Create an instance of {@link LinkedTxnType }
     * 
     */
    public LinkedTxnType createLinkedTxnType() {
        return new LinkedTxnType();
    }

    /**
     * Create an instance of {@link ShipMethodRefType }
     * 
     */
    public ShipMethodRefType createShipMethodRefType() {
        return new ShipMethodRefType();
    }

    /**
     * Create an instance of {@link BillAddressType }
     * 
     */
    public BillAddressType createBillAddressType() {
        return new BillAddressType();
    }

    /**
     * Create an instance of {@link TxnDateRangeFilterType }
     * 
     */
    public TxnDateRangeFilterType createTxnDateRangeFilterType() {
        return new TxnDateRangeFilterType();
    }

    /**
     * Create an instance of {@link InventorySiteLocationRefType }
     * 
     */
    public InventorySiteLocationRefType createInventorySiteLocationRefType() {
        return new InventorySiteLocationRefType();
    }

    /**
     * Create an instance of {@link SalesOrderQueryRqType }
     * 
     */
    public SalesOrderQueryRqType createSalesOrderQueryRqType() {
        return new SalesOrderQueryRqType();
    }

    /**
     * Create an instance of {@link ClassRefType }
     * 
     */
    public ClassRefType createClassRefType() {
        return new ClassRefType();
    }

    /**
     * Create an instance of {@link CustomerSalesTaxCodeRefType }
     * 
     */
    public CustomerSalesTaxCodeRefType createCustomerSalesTaxCodeRefType() {
        return new CustomerSalesTaxCodeRefType();
    }

    /**
     * Create an instance of {@link CustomerMsgRefType }
     * 
     */
    public CustomerMsgRefType createCustomerMsgRefType() {
        return new CustomerMsgRefType();
    }

    /**
     * Create an instance of {@link CurrencyFilterType }
     * 
     */
    public CurrencyFilterType createCurrencyFilterType() {
        return new CurrencyFilterType();
    }

    /**
     * Create an instance of {@link ItemRefType }
     * 
     */
    public ItemRefType createItemRefType() {
        return new ItemRefType();
    }

    /**
     * Create an instance of {@link SalesTaxCodeRefType }
     * 
     */
    public SalesTaxCodeRefType createSalesTaxCodeRefType() {
        return new SalesTaxCodeRefType();
    }

    /**
     * Create an instance of {@link ShipAddressType }
     * 
     */
    public ShipAddressType createShipAddressType() {
        return new ShipAddressType();
    }

    /**
     * Create an instance of {@link TermsRefType }
     * 
     */
    public TermsRefType createTermsRefType() {
        return new TermsRefType();
    }

    /**
     * Create an instance of {@link CustomerRefType }
     * 
     */
    public CustomerRefType createCustomerRefType() {
        return new CustomerRefType();
    }

    /**
     * Create an instance of {@link TemplateRefType }
     * 
     */
    public TemplateRefType createTemplateRefType() {
        return new TemplateRefType();
    }

    /**
     * Create an instance of {@link SalesOrderQueryRsType }
     * 
     */
    public SalesOrderQueryRsType createSalesOrderQueryRsType() {
        return new SalesOrderQueryRsType();
    }

    /**
     * Create an instance of {@link SalesOrderLineRetType }
     * 
     */
    public SalesOrderLineRetType createSalesOrderLineRetType() {
        return new SalesOrderLineRetType();
    }

    /**
     * Create an instance of {@link RefNumberFilterType }
     * 
     */
    public RefNumberFilterType createRefNumberFilterType() {
        return new RefNumberFilterType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QBXMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QBXML")
    public JAXBElement<QBXMLType> createQBXML(QBXMLType value) {
        return new JAXBElement<QBXMLType>(_QBXML_QNAME, QBXMLType.class, null, value);
    }

}
