//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:45:08 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qborderquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.mozu.qbintegration.model.qbmodel.allgen.SalesOrderRet;


/**
 * <p>Java class for SalesOrderQueryRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderQueryRsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SalesOrderRet" type="{}SalesOrderRetType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="statusSeverity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retCount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iteratorRemainingCount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iteratorID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderQueryRsType", propOrder = {
    "salesOrderRet"
})
public class SalesOrderQueryRsType {

    @XmlElement(name = "SalesOrderRet", required = true)
    protected SalesOrderRet salesOrderRet;
    @XmlAttribute(name = "statusCode")
    protected String statusCode;
    @XmlAttribute(name = "statusSeverity")
    protected String statusSeverity;
    @XmlAttribute(name = "statusMessage")
    protected String statusMessage;
    @XmlAttribute(name = "retCount")
    protected String retCount;
    @XmlAttribute(name = "iteratorRemainingCount")
    protected String iteratorRemainingCount;
    @XmlAttribute(name = "iteratorID")
    protected String iteratorID;

    /**
     * Gets the value of the salesOrderRet property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderRetType }
     *     
     */
    public SalesOrderRet getSalesOrderRet() {
        return salesOrderRet;
    }

    /**
     * Sets the value of the salesOrderRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderRetType }
     *     
     */
    public void setSalesOrderRet(SalesOrderRet value) {
        this.salesOrderRet = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusSeverity() {
        return statusSeverity;
    }

    /**
     * Sets the value of the statusSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusSeverity(String value) {
        this.statusSeverity = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the retCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetCount() {
        return retCount;
    }

    /**
     * Sets the value of the retCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetCount(String value) {
        this.retCount = value;
    }

    /**
     * Gets the value of the iteratorRemainingCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteratorRemainingCount() {
        return iteratorRemainingCount;
    }

    /**
     * Sets the value of the iteratorRemainingCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteratorRemainingCount(String value) {
        this.iteratorRemainingCount = value;
    }

    /**
     * Gets the value of the iteratorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteratorID() {
        return iteratorID;
    }

    /**
     * Sets the value of the iteratorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteratorID(String value) {
        this.iteratorID = value;
    }

}
