//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:45:08 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qborderquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesOrderQueryRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderQueryRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TxnID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefNumberCaseSensitive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxReturned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModifiedDateRangeFilter" type="{}ModifiedDateRangeFilterType"/>
 *         &lt;element name="TxnDateRangeFilter" type="{}TxnDateRangeFilterType"/>
 *         &lt;element name="EntityFilter" type="{}EntityFilterType"/>
 *         &lt;element name="RefNumberFilter" type="{}RefNumberFilterType"/>
 *         &lt;element name="RefNumberRangeFilter" type="{}RefNumberRangeFilterType"/>
 *         &lt;element name="CurrencyFilter" type="{}CurrencyFilterType"/>
 *         &lt;element name="IncludeLineItems" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IncludeLinkedTxns" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IncludeRetElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OwnerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="metaData" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iterator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iteratorID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderQueryRqType", propOrder = {
    "txnID",
    "refNumber",
    "refNumberCaseSensitive",
    "maxReturned",
    "modifiedDateRangeFilter",
    "txnDateRangeFilter",
    "entityFilter",
    "refNumberFilter",
    "refNumberRangeFilter",
    "currencyFilter",
    "includeLineItems",
    "includeLinkedTxns",
    "includeRetElement",
    "ownerID"
})
public class SalesOrderQueryRqType {

    @XmlElement(name = "TxnID", required = true)
    protected String txnID;
    @XmlElement(name = "RefNumber", required = true)
    protected String refNumber;
    @XmlElement(name = "RefNumberCaseSensitive", required = true)
    protected String refNumberCaseSensitive;
    @XmlElement(name = "MaxReturned", required = true)
    protected String maxReturned;
    @XmlElement(name = "ModifiedDateRangeFilter", required = true)
    protected ModifiedDateRangeFilterType modifiedDateRangeFilter;
    @XmlElement(name = "TxnDateRangeFilter", required = true)
    protected TxnDateRangeFilterType txnDateRangeFilter;
    @XmlElement(name = "EntityFilter", required = true)
    protected EntityFilterType entityFilter;
    @XmlElement(name = "RefNumberFilter", required = true)
    protected RefNumberFilterType refNumberFilter;
    @XmlElement(name = "RefNumberRangeFilter", required = true)
    protected RefNumberRangeFilterType refNumberRangeFilter;
    @XmlElement(name = "CurrencyFilter", required = true)
    protected CurrencyFilterType currencyFilter;
    @XmlElement(name = "IncludeLineItems", required = true)
    protected String includeLineItems;
    @XmlElement(name = "IncludeLinkedTxns", required = true)
    protected String includeLinkedTxns;
    @XmlElement(name = "IncludeRetElement", required = true)
    protected String includeRetElement;
    @XmlElement(name = "OwnerID", required = true)
    protected String ownerID;
    @XmlAttribute(name = "metaData")
    protected String metaData;
    @XmlAttribute(name = "iterator")
    protected String iterator;
    @XmlAttribute(name = "iteratorID")
    protected String iteratorID;

    /**
     * Gets the value of the txnID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnID() {
        return txnID;
    }

    /**
     * Sets the value of the txnID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnID(String value) {
        this.txnID = value;
    }

    /**
     * Gets the value of the refNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNumber() {
        return refNumber;
    }

    /**
     * Sets the value of the refNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNumber(String value) {
        this.refNumber = value;
    }

    /**
     * Gets the value of the refNumberCaseSensitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNumberCaseSensitive() {
        return refNumberCaseSensitive;
    }

    /**
     * Sets the value of the refNumberCaseSensitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNumberCaseSensitive(String value) {
        this.refNumberCaseSensitive = value;
    }

    /**
     * Gets the value of the maxReturned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxReturned() {
        return maxReturned;
    }

    /**
     * Sets the value of the maxReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxReturned(String value) {
        this.maxReturned = value;
    }

    /**
     * Gets the value of the modifiedDateRangeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedDateRangeFilterType }
     *     
     */
    public ModifiedDateRangeFilterType getModifiedDateRangeFilter() {
        return modifiedDateRangeFilter;
    }

    /**
     * Sets the value of the modifiedDateRangeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedDateRangeFilterType }
     *     
     */
    public void setModifiedDateRangeFilter(ModifiedDateRangeFilterType value) {
        this.modifiedDateRangeFilter = value;
    }

    /**
     * Gets the value of the txnDateRangeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link TxnDateRangeFilterType }
     *     
     */
    public TxnDateRangeFilterType getTxnDateRangeFilter() {
        return txnDateRangeFilter;
    }

    /**
     * Sets the value of the txnDateRangeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnDateRangeFilterType }
     *     
     */
    public void setTxnDateRangeFilter(TxnDateRangeFilterType value) {
        this.txnDateRangeFilter = value;
    }

    /**
     * Gets the value of the entityFilter property.
     * 
     * @return
     *     possible object is
     *     {@link EntityFilterType }
     *     
     */
    public EntityFilterType getEntityFilter() {
        return entityFilter;
    }

    /**
     * Sets the value of the entityFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityFilterType }
     *     
     */
    public void setEntityFilter(EntityFilterType value) {
        this.entityFilter = value;
    }

    /**
     * Gets the value of the refNumberFilter property.
     * 
     * @return
     *     possible object is
     *     {@link RefNumberFilterType }
     *     
     */
    public RefNumberFilterType getRefNumberFilter() {
        return refNumberFilter;
    }

    /**
     * Sets the value of the refNumberFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefNumberFilterType }
     *     
     */
    public void setRefNumberFilter(RefNumberFilterType value) {
        this.refNumberFilter = value;
    }

    /**
     * Gets the value of the refNumberRangeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link RefNumberRangeFilterType }
     *     
     */
    public RefNumberRangeFilterType getRefNumberRangeFilter() {
        return refNumberRangeFilter;
    }

    /**
     * Sets the value of the refNumberRangeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefNumberRangeFilterType }
     *     
     */
    public void setRefNumberRangeFilter(RefNumberRangeFilterType value) {
        this.refNumberRangeFilter = value;
    }

    /**
     * Gets the value of the currencyFilter property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyFilterType }
     *     
     */
    public CurrencyFilterType getCurrencyFilter() {
        return currencyFilter;
    }

    /**
     * Sets the value of the currencyFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyFilterType }
     *     
     */
    public void setCurrencyFilter(CurrencyFilterType value) {
        this.currencyFilter = value;
    }

    /**
     * Gets the value of the includeLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeLineItems() {
        return includeLineItems;
    }

    /**
     * Sets the value of the includeLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeLineItems(String value) {
        this.includeLineItems = value;
    }

    /**
     * Gets the value of the includeLinkedTxns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeLinkedTxns() {
        return includeLinkedTxns;
    }

    /**
     * Sets the value of the includeLinkedTxns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeLinkedTxns(String value) {
        this.includeLinkedTxns = value;
    }

    /**
     * Gets the value of the includeRetElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeRetElement() {
        return includeRetElement;
    }

    /**
     * Sets the value of the includeRetElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeRetElement(String value) {
        this.includeRetElement = value;
    }

    /**
     * Gets the value of the ownerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerID() {
        return ownerID;
    }

    /**
     * Sets the value of the ownerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerID(String value) {
        this.ownerID = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaData(String value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the iterator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterator() {
        return iterator;
    }

    /**
     * Sets the value of the iterator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterator(String value) {
        this.iterator = value;
    }

    /**
     * Gets the value of the iteratorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteratorID() {
        return iteratorID;
    }

    /**
     * Sets the value of the iteratorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteratorID(String value) {
        this.iteratorID = value;
    }

}
