//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:45:08 PM IST 
//


package com.mozu.qbintegration.model.qbmodel.qborderquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxnDateRangeFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxnDateRangeFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromTxnDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToTxnDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateMacro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxnDateRangeFilterType", propOrder = {
    "fromTxnDate",
    "toTxnDate",
    "dateMacro"
})
public class TxnDateRangeFilterType {

    @XmlElement(name = "FromTxnDate", required = true)
    protected String fromTxnDate;
    @XmlElement(name = "ToTxnDate", required = true)
    protected String toTxnDate;
    @XmlElement(name = "DateMacro", required = true)
    protected String dateMacro;

    /**
     * Gets the value of the fromTxnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromTxnDate() {
        return fromTxnDate;
    }

    /**
     * Sets the value of the fromTxnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromTxnDate(String value) {
        this.fromTxnDate = value;
    }

    /**
     * Gets the value of the toTxnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToTxnDate() {
        return toTxnDate;
    }

    /**
     * Sets the value of the toTxnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToTxnDate(String value) {
        this.toTxnDate = value;
    }

    /**
     * Gets the value of the dateMacro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateMacro() {
        return dateMacro;
    }

    /**
     * Sets the value of the dateMacro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateMacro(String value) {
        this.dateMacro = value;
    }

}
